### PR TITLE
Remove vendor script

### PR DESCRIPTION
**Pull request by macdonst**
@brianleroux why do we need the vendor folder and script? Is it a npm caching issue? It's a npm caching issue isn't it?

Signed-off-by: macdonst <simon.macdonald@gmail.com>

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
@macdonst I know we looked at this together, but where did we net out after @brianleroux weighed in?

**Comment by macdonst** [comment]
@kristoferjoseph I don't think @brianleroux has taken another look at this one but from what I remember of the conversation I had with him is that npm caching would prevent us from removing vendoring.

**Comment by kristoferjoseph** [comment]
OK I verified that this is to combat the double cache that npm employs

**Comment by macdonst** [comment]
@kristoferjoseph so we should probably close this PR.

**Comment by tbeseda** [comment]
I'm going to close this in favor of #8 where we take a bit of a hybrid approach and I re-use some ideas from here.
Let's discuss implementation there.

**Pull request closed without merging**
